# Generated by Django 5.1 on 2025-06-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bamboo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bamboo',
            name='image',
        ),
        migrations.CreateModel(
            name='BambooImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bamboo_images/')),
                ('bamboo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.bamboo')),
            ],
        ),
    ]
