# Generated by Django 5.1 on 2025-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sale_bamboo_product_alter_sale_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='bamboo_product',
        ),
        migrations.RemoveField(
            model_name='bambooimage',
            name='bamboo',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Water Bottle', 'Water Bottle'), ('Bamboo Bottle', 'Bamboo Bottle')], default='Water Bottle', max_length=50),
        ),
        migrations.DeleteModel(
            name='Bamboo',
        ),
        migrations.DeleteModel(
            name='BambooImage',
        ),
    ]
