# Generated by Django 5.1 on 2025-06-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Water Bottle', 'Water Bottle'), ('Bamboo Bottle', 'Bamboo Bottle'), ('New Arrivals', 'New Arrivals')], default='Water Bottle', max_length=50),
        ),
    ]
